exclude: 'data|dependencies|experiments|pretrained_models|__pycache__'

default_language_version:
        python: python3

repos:
  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.2
    hooks:
      - id: ufmt
        additional_dependencies: 
          - black == 22.3.0
          - usort == 1.0.2

